### ISSUE TITLE
zoomToBounds-Method

### ISSUE THREAD

**Issue by kscfan2** [ClemensFischer/FX-Map-Control#1]
Is it possible that the method **zoomToBounds ()** has a bug ? 
If I use the method with a southwest and northeast Location both in  one city then the map zoom out to the whole world ? 

Thanks for Help!

**Comment by ClemensFischer** [comment]
Yes, there is a bug. I'll take a look at it.

**Comment by kscfan2** [comment]
I used it with following Locations: 

`map.zoomToBounds(new Location(49.012422, 8.418251), new Location(49.013332, 8.419671));`

**Comment by ClemensFischer** [comment]
Fixed. I'll release it asap.

**Comment by ClemensFischer** [comment]
I've updated MapBase.java. The zoomToBounds method now has a MapBoundingBox argument.

**Comment by kscfan2** [comment]
Thanks for your Help !
