### ISSUE TITLE
Licence to clarify how the control can be used

### ISSUE THREAD

**Issue by hallvard** [ClemensFischer/FX-Map-Control#2]
I would like to use this control in an example project in a university course on agile development. The design is clean, understandable and powerful, so it's a good example of object-oriented design, as well as useful. BTW, we have tried GMapsFX, but it seems buggy and brittle.

In the course, we use maven, but without a release into a repository we either need to clone it into a common repo and release or install it locally or make each student group clone it into their own repo.  However, there is no licence telling us what we can or cannot do. Could you clarify what use is OK, or perhaps release and deploy into a maven repo so we can depend on it.

**Comment by ClemensFischer** [comment]
Added LICENSE

**Comment by hallvard** [comment]
Thanks! Both for the choice of licence and the quick response!
